### ISSUE TITLE
other OS disks able to be used?

### ISSUE THREAD

**Issue by WolfgangBlack** [skiphansen/pano_z80#1]
I couldn't find any email address so I am asking this here.
Can you rename any of the z80 pack OS disks "DRIVEA.DSK" from /z80pack/cpmsim/disks/library/ to boot other OSes on this Pano Z80?
I have a G1 coming in a few days and was hoping to be able to mess with CP/M and other OSes in the z80 pack.

**Comment by skiphansen** [comment]
Some of the other OS disks will probably work, but I didn't implement all of the BIOS features needed for MP/M, i.e. serial ports for multiple users and the timer.  

After you clone the repository look at the git log and you'll find an email address.  I also hang out on the panologic gitter chat .. https://gitter.im/panologic/community

**Comment by WolfgangBlack** [comment]
Thanks!
